# Generated by Django 6.0.4 on 2026-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=150, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
