# Generated by Django 6.0.4 on 2026-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Designates whether this user is suspended and all authenticated privileges revoked', verbose_name='suspended'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user is verified. Default is false pending email verification.', verbose_name='active'),
        ),
    ]
