version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      REDIS_URI: ${REDIS_URI:-redis://redis:6379/0}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL:-http://localhost:3000}
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS:-True}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    depends_on:
      - redis
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3

  redis:
    image: redis:7-alpine
    restart: unless-stopped
