# Generated by Django 6.0.4 on 2026-05-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_site_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor_id', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=2048)),
                ('referrer', models.URLField(blank=True, max_length=2048, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('medium', models.CharField(blank=True, default='', max_length=50)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('browser', models.CharField(blank=True, max_length=64, null=True)),
                ('os', models.CharField(blank=True, max_length=64, null=True)),
                ('device_type', models.CharField(blank=True, max_length=32, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sites.site')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', '-timestamp'], name='tracking_ev_site_id_16ec71_idx'), models.Index(fields=['visitor_id'], name='tracking_ev_visitor_4e6909_idx')],
            },
        ),
    ]
