# Generated by Django 6.0.4 on 2026-05-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='screen_width',
        ),
    ]
