# Generated by Django 6.0.4 on 2026-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_event_screen_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='continent',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
