# Generated by Django 6.0.4 on 2026-05-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_event_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='continent',
        ),
    ]
