# Generated by Django 6.0.4 on 2026-05-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_site_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrowserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('browser', models.CharField(max_length=64)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_browser_stats', to='sites.site')),
            ],
            options={
                'ordering': ['-visitors'],
                'unique_together': {('site', 'date', 'browser')},
            },
        ),
        migrations.CreateModel(
            name='DailyCountryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('country', models.CharField(max_length=100)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_country_stats', to='sites.site')),
            ],
            options={
                'ordering': ['-visitors'],
                'unique_together': {('site', 'date', 'country')},
            },
        ),
        migrations.CreateModel(
            name='DailyDeviceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('device_type', models.CharField(max_length=32)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_device_stats', to='sites.site')),
            ],
            options={
                'ordering': ['-visitors'],
                'unique_together': {('site', 'date', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyOSStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('os', models.CharField(max_length=64)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_os_stats', to='sites.site')),
            ],
            options={
                'ordering': ['-visitors'],
                'unique_together': {('site', 'date', 'os')},
            },
        ),
        migrations.CreateModel(
            name='DailyPageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.TextField()),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_page_stats', to='sites.site')),
            ],
            options={
                'ordering': ['-pageviews'],
                'unique_together': {('site', 'date', 'path')},
            },
        ),
        migrations.CreateModel(
            name='DailyReferrerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=50)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_referrer_stats', to='sites.site')),
            ],
            options={
                'ordering': ['-pageviews'],
                'unique_together': {('site', 'date', 'source', 'medium')},
            },
        ),
        migrations.CreateModel(
            name='DailySiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='sites.site')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
