# Generated by Django 6.0.4 on 2026-05-12 20:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysitestats',
            name='avg_visit_duration',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='bounce_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='total_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='views_per_visit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
