# Generated by Django 6.0.4 on 2026-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailysitestats_avg_visit_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysitestats',
            name='avg_visit_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysitestats',
            name='bounce_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
