# Generated by Django 6.0.4 on 2026-05-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_dailysitestats_avg_visit_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysitestats',
            name='avg_visit_duration',
        ),
        migrations.RemoveField(
            model_name='dailysitestats',
            name='bounce_rate',
        ),
        migrations.RemoveField(
            model_name='dailysitestats',
            name='views_per_visit',
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='single_page_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='total_pageview_in_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Total no of pageviews that were part of a visit (session)'),
        ),
        migrations.AddField(
            model_name='dailysitestats',
            name='totla_duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all session lengths'),
        ),
        migrations.AlterField(
            model_name='dailysitestats',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, help_text='Total sessions in a day'),
        ),
    ]
