# Generated by Django 6.0.4 on 2026-05-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_dailysitestats_avg_visit_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysitestats',
            old_name='totla_duration_seconds',
            new_name='total_duration_seconds',
        ),
        migrations.RenameField(
            model_name='dailysitestats',
            old_name='total_pageview_in_sessions',
            new_name='total_pageviews_in_sessions',
        ),
    ]
