# Generated by Django 6.0.4 on 2026-05-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_rename_totla_duration_seconds_dailysitestats_total_duration_seconds_and_more'),
        ('sites', '0002_site_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailypagestats',
            old_name='path',
            new_name='url',
        ),
        migrations.AlterUniqueTogether(
            name='dailypagestats',
            unique_together={('site', 'date', 'url')},
        ),
    ]
