# Generated by Django 6.0.4 on 2026-05-09 20:26
import uuid
from django.db import migrations, models

def generate_public_ids(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    for site in Site.objects.all().iterator():
        site.public_id = uuid.uuid4()
        site.save(update_fields=['public_id'])

class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='site',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
            preserve_default=False,
        ),
        # Populate existing rows
        migrations.RunPython(generate_public_ids, reverse_code=migrations.RunPython.noop),
        # Now make the field non-nullable and unique
        migrations.AlterField(
            model_name='site',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
