# Generated by Django 6.0.4 on 2026-05-20 03:08

import sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='timezone',
            field=models.CharField(choices=sites.models.CachedTimezoneChoices(), default='UTC', max_length=50),
        ),
    ]
