# Generated by Django 6.0.4 on 2026-05-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_site_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='public_id',
        ),
    ]
